### PR TITLE
fix(cmd): correct permissions of created files and folders

### PR DESCRIPTION
**Pull request by dmvolod**
Fixed incorrect folder permission introduced by the #72. Also added `build` target in mage for development purposes

### CODE REVIEW

**Review by luisdavim — APPROVED** [review]
LGTM

**Comment by luisdavim** [comment]
@princjef can we get this merged and tagged? The latest version is broken and installing the tool with `@latest` provides a bad experience...

**Review by princjef — APPROVED** [review]

**Comment by princjef** [comment]
Yep lgtm thanks for the fix

**Comment by princjef** [comment]
Merged and tagged v0.4.1. Thanks folks!

**Pull request merged**
